package com.iran31124.bimeh;

import android.app.*; import android.os.*; import android.content.*; import android.graphics.Color; import android.view.*; import android.widget.*; import java.util.*;

public class MainActivity extends Activity {
 LinearLayout root, list; ArrayList<String> items=new ArrayList<>();
 int pad=28;
 @Override public void onCreate(Bundle b){super.onCreate(b); showHome();}
 TextView tv(String s,int size){ TextView t=new TextView(this); t.setText(s); t.setTextSize(size); t.setTextColor(Color.DKGRAY); t.setPadding(pad,pad,pad,pad); t.setGravity(Gravity.RIGHT|Gravity.CENTER_VERTICAL); return t; }
 Button btn(String s){ Button x=new Button(this); x.setText(s); x.setTextSize(15); return x; }
 void base(String title){ root=new LinearLayout(this); root.setOrientation(LinearLayout.VERTICAL); root.setPadding(18,18,18,18); root.setLayoutDirection(View.LAYOUT_DIRECTION_RTL); TextView h=tv(title,23); h.setTextColor(Color.rgb(20,85,145)); root.addView(h,new LinearLayout.LayoutParams(-1,80)); ScrollView sv=new ScrollView(this); list=new LinearLayout(this); list.setOrientation(LinearLayout.VERTICAL); sv.addView(list); root.addView(sv,new LinearLayout.LayoutParams(-1,0,1)); setContentView(root); }
 void showHome(){ base("مدیریت اقساط بیمه ایران"); list.addView(tv("نمایندگی بیمه ایران\nکد 31124",20)); Button add=btn("➕ ثبت بیمه‌نامه جدید"); add.setOnClickListener(v->showAdd()); list.addView(add); Button all=btn("📋 بیمه‌نامه‌ها و اقساط"); all.setOnClickListener(v->showList()); list.addView(all); list.addView(tv("امکانات: ثبت مشتری، محاسبه اقساط، وضعیت پرداخت و اقساط معوق",16)); }
 void showAdd(){ base("ثبت بیمه‌نامه"); EditText name=new EditText(this); name.setHint("نام و نام خانوادگی"); list.addView(name); EditText phone=new EditText(this); phone.setHint("شماره تلفن"); phone.setInputType(3); list.addView(phone); EditText policy=new EditText(this); policy.setHint("شماره بیمه‌نامه"); list.addView(policy); EditText total=new EditText(this); total.setHint("مبلغ کل (تومان)"); total.setInputType(2); list.addView(total); EditText count=new EditText(this); count.setHint("تعداد اقساط"); count.setInputType(2); list.addView(count); Button save=btn("💾 ذخیره"); save.setOnClickListener(v->{String n=name.getText().toString(); if(n.isEmpty()){name.setError("نام را وارد کنید");return;} String row=n+" | بیمه‌نامه: "+policy.getText()+" | مبلغ: "+total.getText()+" | اقساط: "+count.getText(); items.add(row); getPreferences(0).edit().putString("items",String.join("\n",items)).apply(); Toast.makeText(this,"ثبت شد",Toast.LENGTH_SHORT).show(); showHome();}); list.addView(save); Button back=btn("بازگشت"); back.setOnClickListener(v->showHome()); list.addView(back); }
 void showList(){ base("بیمه‌نامه‌ها"); if(items.isEmpty()){String raw=getPreferences(0).getString("items",""); if(!raw.isEmpty()) items.addAll(Arrays.asList(raw.split("\\n")));} if(items.isEmpty()) list.addView(tv("هنوز بیمه‌نامه‌ای ثبت نشده است.",17)); else for(String s:items) list.addView(tv("• "+s,16)); Button back=btn("بازگشت"); back.setOnClickListener(v->showHome()); list.addView(back); }
}
